//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaterials
    {
        public long BranchID { get; set; }
        public long MaterialID { get; set; }
        public Nullable<double> CountPerPiece { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<double> CountForTheAmount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> AddOrDelete { get; set; }
        public Nullable<long> ServiceID { get; set; }
    }
}
