//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> CostPerPiece { get; set; }
        public string NameOfSupplier { get; set; }
        public Nullable<double> TheCostForTheAmount { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string Description { get; set; }
    }
}
