//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientEntities : DbContext
    {
        public ClientEntities()
            : base("name=ClientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<BranchMaterials> BranchMaterials { get; set; }
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<CabinetServices> CabinetServices { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceMaterials> ServiceMaterials { get; set; }
        public virtual DbSet<ServiceWorkers> ServiceWorkers { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<SessionServices> SessionServices { get; set; }
        public virtual DbSet<SessionWorkers> SessionWorkers { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkerWorkingHours> WorkerWorkingHours { get; set; }
        public virtual DbSet<WorkingHour> WorkingHour { get; set; }
    }
}
