//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionWorkers
    {
        public long SessionID { get; set; }
        public long WorkerID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }
}
