//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionServices
    {
        public long SessionID { get; set; }
        public long ServiceID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<bool> PayState { get; set; }
        public long WorkerID { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string Description { get; set; }
        public Nullable<long> CabinetID { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Service Service { get; set; }
        public virtual Session Session { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
