//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Pay = new HashSet<Pay>();
            this.SessionServices = new HashSet<SessionServices>();
            this.WorkingHour = new HashSet<WorkingHour>();
        }
    
        public long Id { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string Name { get; set; }
        public Nullable<long> Experience { get; set; }
        public string Position { get; set; }
        public string TattooStyle { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay> Pay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionServices> SessionServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingHour> WorkingHour { get; set; }
    }
}
