//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_TS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHour
    {
        public long Id { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> WorkerID { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
